# Generated by Django 4.2.2 on 2023-06-19 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=7)),
                ('red', models.CharField(max_length=3)),
                ('blue', models.CharField(max_length=3)),
                ('green', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Mural',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
                ('imagen', models.BinaryField()),
                ('descripcion', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('altitud', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Muralista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('seudonimo', models.CharField(max_length=100)),
                ('foto', models.BinaryField()),
                ('celular', models.CharField(max_length=9)),
                ('user_instagram', models.CharField(max_length=30)),
                ('user_facebook', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=250)),
                ('contrasena', models.CharField(max_length=60)),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('id_mural', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descub.mural')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descub.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Paleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descub.color')),
                ('id_mural', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descub.mural')),
            ],
        ),
        migrations.AddField(
            model_name='mural',
            name='id_muralista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descub.muralista'),
        ),
    ]
