# Generated by Django 4.2.2 on 2023-06-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muralista',
            name='foto',
            field=models.BinaryField(null=True),
        ),
    ]
