# Generated by Django 4.2.2 on 2023-06-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descub', '0002_alter_muralista_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mural',
            name='imagen',
            field=models.BinaryField(null=True),
        ),
    ]
